networks:
  hardcode-net:
    driver: bridge

services:
  server:
    image: server
    build:
      context: ./server/
    networks:
      - hardcode-net
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
  
  judge:
    image: judge
    build:
      context: ./codejudge/
    networks:
      - hardcode-net
    volumes:
      - ./codejudge:/app
  
  client:
    image: client
    build:
      context: ./client/
    ports:
      - "5173:5173"
    volumes:
    - ./client:/app

  rabbitmq:
    image: rabbitmq_custom
    build:
      context: ./rabbitmq/
    networks:
      - hardcode-net
    ports:
      - "5672:5672"
      - "15672:15672"
