apiVersion: v1
kind: Service
metadata:
  name: hc-client-service
spec:
  selector:
    app: hc-client
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30001
  type: NodePort

---
